### ISSUE TITLE
Glitche in animation

### ISSUE THREAD

**Issue by Serhioromano** [Hendrixer/ngFx#66]
I am using UI Router

    <div ui-view class="fx-fade-left"></div>

But here is what happens.

http://www.screencast.com/t/bO5j8MiF2bl

**Comment by chrispaynter** [comment]
I know that this has been closed, but I wanted to post this solution, which I've been using with some success for smooth view transitions and ngFx. Please note I haven't cross browser checked thoroughly yet. Also I think it can be optimized somewhat, especially the z-index. I hope it can help someone.

Add the 'animated-view' class to the same element that has the 'fx-' class.

Example

```
<div class="fx-bounce-down animated-view" ng-show="currentStep == 'entry'">
    // Markup for this view
</div>
```

Code

```
.animated-view {
    position: static;
    width: 100%;

    &.visible {
        position: static;
    }

    &.ng-hide-add, .ng-hide-remove {
    }


    &.ng-hide.add {
        position: absolute;
        z-index: 5;
    }

    &.ng-hide-add-active {
        position: absolute;
    }

    &.ng-hide {
        z-index: 3;
        position: absolute;
    }

    &.ng-hide-remove {
        position: static;
    }
}

```

**Comment by Hendrixer** [comment]
this is awesome!

Scott Moss
Software Engineer
closurelog.com
P: 415-857-4618

**Comment by Serhioromano** [comment]
That is what I thought that `position:absolute` can fix this issue.

**Comment by DaAwesomeP** [comment]
I have the same exact problem with ngRoute, but is there an alternative to `currentStep` for it? I can't figure out the solution.
