### ISSUE TITLE
Error: error:unpr Unknown Provider

### ISSUE THREAD

**Issue by bhuwan-arora** [Hendrixer/ngFx#71]
Getting the following error with angularjs 1.2.13
 ```
Unknown provider: $$qProvider <- $$q <- $animate <- $compile
```

Tried with and without ng-animate
```
var websiteApp = angular.module('websiteApp', ['ngRoute', 'ngAnimate', 'ngFx']);
```
```
var websiteApp = angular.module('websiteApp', ['ngRoute', 'ngFx']);
```

whats the issue?

**Comment by Hendrixer** [comment]
This should be fixed

**Comment by staffup-dave** [comment]
Looks like the error's changed a tad - I'm getting this with 1.3.3 and the most recent ngFxBundle

````javascript
[$injector:unpr] Unknown provider: $$jqLiteProvider <- $$jqLite <- $animate <- $compile
````

Not sure if it matters but jquery-2.1.1 is being used.

Let me know if you want me to paste the full error stack.

**Comment by Hendrixer** [comment]
Could you paste the full stack please? In the mean time, don't use the
bundle, include ngAnimate and gsap/tweenmax.js yourself. I think that's
going to solve the problem.

**Comment by staffup-dave** [comment]
@Hendrixer it was because angular was 1.3.3 and current rev is 1.3.14 - once I updated angular to current it worked (hence why I deleted my comment). 

I suspect it was due to the bundled version of animate being newer than my base angular.

**Comment by Hendrixer** [comment]
That's exactly right. I might just get rid of the bundle.

**Comment by staffup-dave** [comment]
If you put a note in the dependencies section I think that would suffice. The way it reads now says "as long as you have angular > 1.2 you're golden. 

Maybe change it to "if you're using the bundle you must ensure the angular.js you load is at current release due to animate.js dependencies"

**Comment by Hendrixer** [comment]
Good idea
