### ISSUE TITLE
Can't find variable: TweenMax

### ISSUE THREAD

**Issue by philbot5000** [Hendrixer/ngFx#83]
Great animation library!

Starting today I haven't been able to build my project with the error: can't find variable TweenMax. I noticed there was a recent PR merged, but it seems pretty harmless. Not sure what's going on, but it has all of the sudden popped up in two of my projects using ngFx. It certainly could be user error but I'd be intersted to see if anyone else is experiencing this problem.

**Comment by snehilmodani** [comment]
+1

**Comment by 4xposed** [comment]
same problem here

**Comment by shoonoise** [comment]
:+1:

**Comment by WSquared** [comment]
Same here.

**Comment by Hendrixer** [comment]
Sorry about that guys, I am going to start making a change log, but I updated the docs. To make sure everything still works, use `ngFxBundle.js` instead. `ngFx.js` dopes not come bundled now with gsap or ngAnimate.

**Comment by cgarnier** [comment]
Could you be a little more strict about changing verion number ? 1.0.5 -> 1.0.6 was not a hot fix.
Your project  is pretty cool but each intall fucked up my project.

**Comment by Hendrixer** [comment]
Yea, that was pretty lame of me. I made this before I knew of semver

**Comment by Hendrixer** [comment]
now that I'm already deep into it, do you have any recommended approached now @cgarnier

**Comment by thedug** [comment]
What is the recommended fix here?

**Comment by cgarnier** [comment]
You juste have to include TwinMax from your bower directory in your app.

@Hendrixer could you tag this version as 0.1.0 or somtehing? Just to take a new start :P

**Comment by cgarnier** [comment]
1.1.0

**Comment by Hendrixer** [comment]
@cgarnier yea, I did not know about semver back then. Sorry guys. Yea, I was thinking about how to start over and 1.1.0 should do it. Working on this all day today actually, more animations and all! New build system, easier for you guys to get in and actually add some animations

**Comment by thedug** [comment]
@cgarnier Did you mean TweenMax? Which version?

**Comment by cgarnier** [comment]
You just need to use ngFxBundle.js

**Comment by Hendrixer** [comment]
I have now upgraded to `v1.1.0` and have gotten rid of the bundle file. It and along with all the versioning issues have caused a headache. I've also added `static` animations. Check the [CHANGELOG](https://github.com/Hendrixer/ngFx/blob/master/CHANGELOG.md) which I have added as well and plan to keep up regularly.

**Comment by cgarnier** [comment]
TY, nice job!

**Comment by SagiMedina** [comment]
I'm still get the Uncaught ReferenceError: TweenMax is not defined

**Comment by cdipaolo** [comment]
^ Same. Just got the error

**Comment by sfrenchy** [comment]
I'm still getting this error with v1.1.0
```javascript
ngFx.js:1429 Uncaught ReferenceError: TweenMax is not defined
    (anonymous function) @ ngFx.js:1429
```

**Comment by shivpat** [comment]
Same error here. Any update?

**Comment by cdipaolo** [comment]
If you manually load the TweenMax library it goes away but there should be
a better fix implemented I think

**Comment by shivpat** [comment]
I'm loading TweenMax on my html page "<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.17.0/TweenMax.min.js"></script>", but it is still not working. Do I need to declare it as a dependency as well?

**Comment by nhduc296** [comment]
same here

**Comment by jasonshark** [comment]
adding this cdn `<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.17.0/TweenMax.min.js"></script>` solved the TweenMax is not defined for me

**Comment by fangtingprahl** [comment]
I have the same problem:
Uncaught ReferenceError: TweenMax is not defined(anonymous function) @ ngFx.js:1429

**Comment by seetpal-smartshore** [comment]
Thanks cleechtech,

its resolved bcz of u

**Comment by akarchie164** [comment]
I included TweenMax.min.js but still issue is not solved.
