### ISSUE TITLE
add bundle and un bundle file

### ISSUE THREAD

**Issue by adamchenwei** [Hendrixer/ngFx#86]
May I know what it means "add bundle and un bundle file"?
Sorry I am pretty new.

Also, may I know if there is a plan to versioning the library? Because its kinda really hard to see what have changed from one version to another if anything has been done. Its just really pain has to go back and read comment of each commit...

Not sure if its reasonable :)

Thanks

**Comment by Hendrixer** [comment]
This is totally reasonable and I should be doing this.

**Comment by Hendrixer** [comment]
yea, sorry about that. This was created before I knew about semver. Going in today and fixing that. The bundle is ngFx with all the dependencies it needs to work.

**Comment by Hendrixer** [comment]
all fixed in version 1.1.0
