### ISSUE TITLE
Emit Events with element information

### ISSUE THREAD

**Issue by ahetawal** [Hendrixer/ngFx#87]
Hi,
I am trying to use the emit events something like this - 
$scope.$on('fade-normal:enter', function () {
    console.log('fade enter');
  });

But since this animation is being applied to many of my elements, It would be real helpful, if you can pass the element information on whose animation this event was emitted, then I can use it for deriving what different  steps I need to take. Currently I cannot figure out which element just completed it animation and what should I do next.
Hope this makes sense.

Thanks again for the awesome work...

**Comment by Hendrixer** [comment]
That makes sense, I can pass the element itself as an arg on the event.

**Comment by Hendrixer** [comment]
check out the issue #89
